### PR TITLE
Add support for long arrrays

### PR DESCRIPTION
**Pull request by phit**
Based on my work in https://github.com/minecraft-dotnet/Substrate/pull/48
Have done 0 testing, and almost no experience in Visual Studio. So please let me know if I screwed up majorly, but looking over it seems fine to me.

Closes https://github.com/jaquadro/NBTExplorer/issues/59 & https://github.com/jaquadro/NBTExplorer/issues/60

### CODE REVIEW

**Comment by williewillus** [comment]
Built this and it seems to work on the 1.13 chunks which use the new long array. Thanks!

**Comment by phit** [comment]
creating new long arrays doesn't seem to work, they just display as byte tag.. not sure where i screwed up, but for viewing and editing existing ones it seems to work fine

**Comment by jaquadro** [comment]
Oh, I'm sorry I somehow missed this.  I saw the PR for substrate but not here, so I ended up implementing the support.

Ever since Github retooled their feed, I've lost all notifications on my projects.

**Comment by jaquadro** [comment]
Thanks for putting this together though.  You did catch a couple things that I missed in my changeset.

**Comment by phit** [comment]
all good, glad it was at least somewhat helpful!

**Pull request closed without merging**
